MODEL:
  BERT_CKPT: "hfl/chinese-macbert-base"
  DETECT_MODEL: "hfl/chinese-electra-180g-base-discriminator"
  DEVICE: "cuda"
  NAME: "macbert4csc"
  GPU_IDS: [0,1,2,3]
  # [loss_coefficient]
  HYPER_PARAMS: [0.4]
  CORRECT_LOSS_WEIGHTS: [0.8]
  NCE_LOSS_WEIGHTS: [0.4]
  KLOSS_WEIGHTS: [0.4]
  DETECT_LOSS_WEIGHTS: [0.4]

  STEP: [0.125]
  #WEIGHTS: "output/macbert4csc/epoch=6-val_loss=0.07.ckpt"
  WEIGHTS: ""

DATASETS:
  TRAIN: "/var/zgcCorrector/data/data/cp.txt"
  TRAIN13_14_15: "/var/zgcCorrector/data/data/13_14_15.txt"
  VALID13: "/var/zgcCorrector/data/data/test13.txt"
  VALID14: "/var/zgcCorrector/data/data/test14.txt"
  VALID15: "/var/zgcCorrector/data/data/test15.txt"

SOLVER:
  BASE_LR: 5e-5
  WEIGHT_DECAY: 0.01
  BATCH_SIZE: 7
  MAX_EPOCHS: 30
  ACCUMULATE_GRAD_BATCHES: 2

OUTPUT_DIR: "/var/zgcCorrector/output/pt2"
MODE: ["train", "test"]
